### ISSUE TITLE
Entrances

### ISSUE THREAD

**Issue by g-o-o-f** [GoldenJude/Mineshafts#1]
Heya, figured I'd make use of github rather than ping you endlessly over Discord.

---

Would it be possible to let players enter/exit mineshafts with a cart attached and the cart follows through? 
I realise it might not work great with how the current entrance functions by placing you on top of the entry but yeah.

---

Additionally, any chance we might see alternative entrances in terms of visuals? I'd personally love a vertical entrance with either a door, or alternatively, the same sort of entrance/exit that Burial Chambers and Troll Caves have where the entrance is just a dark void and the exit is a bright opening.

**Comment by GoldenJude** [comment]
I do have a bigger update planned for the future in which I could look into carts going through entrances and add some more entrance types.
