### ISSUE TITLE
mineshafts prison - no resource bak after deconstruction Mineshaft Enterance (exit)

### ISSUE THREAD

**Issue by Juraszka** [GoldenJude/Mineshafts#12]
It's possible to deconstruct Mineshafts Enterance (Exit) inside Mineshafts, but there is no resource back and i get stuck inside mineshaft.
Please make exit undestructable.

**Comment by Juraszka** [comment]
or just add resource back

**Comment by GoldenJude** [comment]
entrances give resources back if it is enabled in the config - "recover" option
