### ISSUE TITLE
Permanent thunderstorms when enabled

### ISSUE THREAD

**Issue by Christianfoley** [GoldenJude/Mineshafts#13]
After having a permanent thunderstorm with purple lightning on my server, I pinpointed this mod as the issue. Could be an issue with this mod standalone, but it could also be a conflict issue. Here is the r2modman code for the modprofile that causes this issue: `0184d0dc-6abf-1f60-6813-94c7f30f6724`

**Comment by GoldenJude** [comment]
probably fixed with mistlands update
