### ISSUE TITLE
Wall Collision

### ISSUE THREAD

**Issue by g-o-o-f** [GoldenJude/Mineshafts#2]
~~Encountered a bit of an issue with the "[mb_rope_ladder]" object added through the ValheimRAFT mod in the sense that, when placed against a wall within a mineshaft, it plops you onto the other side of the wall hanging thousands of metres above the ground, very spooky.~~
Never mind this part, I didn't notice that the ladder has a pointer indicating which side the player will be climbing up and down along... My bad.

---

Regardless, I am curious if it would be possible to add some sort of collision detection to prevent players/carts/item drops from going outside the mineshaft walls. I've had plenty of items end up stuck on top of mineshafts or fallen down around my base from the heavens.

**Comment by GoldenJude** [comment]
Hey, I would need some more information about this. I know that the player is able to throw an item through the mineshaft walls if they're right up against the wall, which I might be able to fix. You also mentioned drops, are those drops from breaking mineshaft walls? And finally I would need some information on how to reproduce the issues of players and carts falling through minehafts.

**Comment by g-o-o-f** [comment]
> You also mentioned drops, are those drops from breaking mineshaft walls?

Not really from what I recall, most of these instances have been while I've been building inside the mineshafts and ended up having to deconstruct something that was partially going through a wall/ceiling/floor, leading to items getting stuck above the ceiling or falling down to the ground if the object happened to be sticking out a wall or floor. 

I understand this might be hard to "fix" as it isn't really an issue so much as an inconvenience, and I think an alternative solution would be to increase your pickup range, but that might be a bit cheaty to some.

Unless you can somehow increase pickup range while only inside mineshafts..? Though that doesn't sound like a particularly elegant way to go about it. I know regular terrain forces drops out of it but I have no idea if that can be put to use in this manner by having mineshafts force items that drop near them to always appear on the inside of it.

Like uh, say you have a few wooden beams that the last of which is sticking up above the ceiling, you deconstruct the top one and it drops its wood on top of the shaft. What if instead, as long as an item drops within the range of 1-2 shafts, it "vacuums" the item and shoots it out "inside". Probably just wishful thinking but hey, maybe it can lead to some idea(s).

---
> And finally I would need some information on how to reproduce the issues of players and carts falling through minehafts.

Players falling through mineshafts isn't much of an issue, I believe the issue with carts falling through the floor is simply based on load times. I have a pretty object and terraform intensive world so sometimes it takes a bit to load things and I would assume in some cases, carts end up getting loaded before mineshafts and thus end up dropping from the sky.

The one instance I managed to fall out of a mineshaft myself (which wasn't using the wrong side of a modded ladder... ahem) was when I was sprinting at high speed (Level 100 Run skill, +9% move speed from Fenris set, +10% move speed from passive Eikthyr) and ended up running faster than the mineshafts could load in so I ran over the edge and had a nice view of the world tree as I fell into my base from above (failed my superhero landing unfortunately).

I believe the area the mineshaft took a bit longer to load was at the border of a zone, but I could be wrong.

**Comment by GoldenJude** [comment]
thicklened up the wall collisions, not much more can be done here
