### ISSUE TITLE
r2modman Config editor

### ISSUE THREAD

**Issue by g-o-o-f** [GoldenJude/Mineshafts#3]
I don't know if this is a personal issue but editing the config for Mineshafts through r2modman's Config editor results in all veins in-game being removed, walls no longer drop stone and the recipe for the mineshaft entrance is gone but it remains buildable (albeit free) and you can still exit and enter.

Editing the config manually does not cause these issues.

---
**Update 1**
Only way to fix the config after editing it through r2modman that I have been able to find myself is to completely reinstall the configuration. 

If I edit the config through r2modman and then later attempt to fix it by editing and saving the config manually, the result I got when starting the game back up was me getting caged into a single cube surrounded by indestructible veins.

---
**Update 2**
Reinstalled my config and re-added my custom "vein_tar" and everything got back to normal working order.

**Comment by GoldenJude** [comment]
Tried reproducing this and did not run into any issues when using the r2 editor, can you attach your log and the config file if you are able to?

**Comment by GoldenJude** [comment]
The files can be found by opening the profile folder in R2 
![obrazek](https://user-images.githubusercontent.com/69705529/173752012-6fd73afd-6a95-44da-b658-b1fc43a3ca08.png)

The config file would be in bepinex/config and the log would be in bepinex/logoutput.log
Of course I would need you to edit the config in R2 to what you were trying to change when this issue occured and run the game for the log to display needed information.

**Comment by viper3c** [comment]
GoldenJude I am actually having the same issue, everything seems to work fine until I modify the config file then no more veins spawn and existing veins disappear.  If I delete the config and let the came recreate the default .cfg file it resume operating normally.
[LogOutput.log](https://github.com/GoldenJude/Mineshafts/files/9226654/LogOutput.log)
I have attached the log file you requested above.  I am sure its likely a mod conflict but let me know what you find thanks!

**Comment by GoldenJude** [comment]
should be fixed in latest update
