### ISSUE TITLE
Mineshaft asset loading in broken state

### ISSUE THREAD

**Issue by austinkregel** [GoldenJude/Mineshafts#34]
# What

## Disclaimer
On the outset, this is technically a duplicate of https://github.com/GoldenJude/Mineshafts/issues/31 and https://github.com/GoldenJude/Mineshafts/issues/30, however, I was able to track down where it's getting introduced but I lack the domain knowledge of modding to fix the issue.

After a few hours of debugging and un/commenting features until I was able to isolate the weird texture/weather issue to this chunk of code that loads the location

## Reproduction steps
 1. Download a fresh copy of Valheim
 2. Install this mod, and it's dependencies (BepInEx, etc)
 3. Load any character
 4. Load any world
 5. Spawn the needed materials to create the mineshaft (stonecutter, stone, hammer, etc)
 6. Enter the created mineshaft. 

## Actual issue
Once the world loads, you should see a heavy particle effect and a dense fog as depicted

![Screenshot 2024-12-29 155757](https://github.com/user-attachments/assets/f9315086-31a4-4a71-b36a-34082697bad8)

## Code

https://github.com/GoldenJude/Mineshafts/blob/master/Patches/AddLocation.cs#L22

```cs
var locationParent = gos.Find(go => string.Equals(go.name, "_Locations", StringComparison.Ordinal)).transform.Find("Meadows");

var instantiated = UnityEngine.Object.Instantiate(msLocations, locationParent);
instantiated.FixReferences();
instantiated.GetComponentInChildren<DungeonGenerator>(true).m_themes = (Room.Theme)Main.roomTheme;
```

Specifically the part that seems to "break" is the `transform.Find("Meadows")`. `UnityEngine.Object.Instantiate`'s second parameter needs to be a transform, so leaving off the `Find("Meadows")` leads to the same issue.

My initial impression is that there could be an issue with the mineshaft asset 🤔 but I don't have Unity set up to load/preview the asset.

**Comment by Jaimedarkfyr** [comment]
was you not able to figure this out? ive been dying for a fix... any suggestions?
