### ISSUE TITLE
Min Pickaxe Tier

### ISSUE THREAD

**Issue by g-o-o-f** [GoldenJude/Mineshafts#4]
Updated my mod to version 1.0.3 and suddenly I was unable to mine black metal veins due to being "too hard".

I checked the config and changed all pickaxe tier requirements from:
3 → 2
2 → 1
This fixed the issue.

And from that I gather it goes as follows:
```
Antler Pickaxe = Tier 0
Bronze Pickaxe = Tier 1
Iron Pickaxe = Tier 2
```
Base game has no tier 3 pickaxe.

**Comment by GoldenJude** [comment]
default config fixed
