### ISSUE TITLE
No ores as last update?

### ISSUE THREAD

**Issue by Sreolla22** [GoldenJude/Mineshafts#9]
At work now, but as of yeaterdays update that seems to broke multiple mods, seems to of broke orrs dpawning in the shafts. I had a world save on sunday all worked flawless, but yesterday i made a new world, mined for 45min and not a single ore in any biome using same config as day before. Will double check the configs after work but putting this out case others get it t00

**Comment by GoldenJude** [comment]
you were either unlucky or had a broken config in which case latest update shouldve fixed that
